#hub server teleport
use-hub-server: "false"
hub-server-ip: "000.00.000.00" #if you use WaterdogPE, plese insert the server-name here
hub-server-port: "19132" #if you use WaterdogPE, plese set an empty string here (like: "")

#waterdog (not WDPE) teleport (hub server teleport must be enabled to enable this)
waterdog-hub-teleport: "false"
waterdog-servername: "name"

#random-(/multi-)hubs [true | false]
### Only available with deactivated hub servers
use-random-hubs: "false"

#aliases [true | false]
use-aliases: "true"

#homes [true | false]
use-homes: "true"

#warps [true | false]
use-warps: "true"

#TPAs [true | false]
use-tpas: "true"
tpa-time: 30 #seconds

#Spawn Teleport delay [true | false]
use-spawnDelay: "false"
spawn-delay-seconds: 3

#hub teleport on Join [true | false]
hub-teleport-on-join: "true"

#use Forms [true | false]
use-forms: "true"

################
### Language ###
################
#
# Languages:
# -> 'en_BE' - British English
# -> 'ger_DE' - German
# -> 'fr_FR' - French
# -> 'CUSTOM' - Edit the messages yourself
#
# Chose you language here:
language: "en_BE"


#DON'T CHANGE THIS!!
version: "1.5.3"

############################
##########theSpawn##########
############################
#Licensed under Apache License 2.0! Plugin by supercrafter333 inspirated by MSpawns from EvolSoft!
