#hub server teleport
use-hub-server: "false"
hub-server-ip: "000.00.000.00" #if you use WaterdogPE, please insert the server-name here
hub-server-port: "19132" #if you use WaterdogPE, please set an empty string here (like: "") or the port of your hub-server


#spawns [true | false]
use-spawns: "true"
#Spawn Teleport delay [true | false]
use-spawnDelay: "false"
spawn-delay-seconds: 3

#hub(-s) [true | false]
use-hub: "true"
#hub teleport on join [true | false]
hub-teleport-on-join: "true"
#hub teleport on death [true | false]
hub-teleport-on-death: "true"
#random-(/multi-)hubs [true | false]
### Only available with deactivated hub servers
use-random-hubs: "false"


#aliases [true | false]
use-aliases: "true"

#homes [true | false]
use-homes: "true"

#use max home permissions [true | false]
use-max-home-permissions: "false"

#warps [true | false]
use-warps: "true"

#player-warps [true | false]
use-playerwarps: "true"

#maximum permission for player-warps [true | false]
use-max-playerwarps-permissions: "false"

#TPAs [true | false]
use-tpas: "true"
tpa-time: 30 #seconds

#use Forms [true | false]
use-forms: "true"

#use Toast-Notifications [true | false]
use-toast-notifications: "true"

# /back command for  return to the point where you have died [true | false]
use-back-command: "true"
# maximum time in which the player can return to the point of death, setting it to "0" will make it possible for the player to use it whenever he wants
### IN MINUTES ###
back-time: 15

################
### Language ###
################
#
# Languages:
# -> 'en_BE' - British English
# -> 'ger_DE' - German
# -> 'es_ES' - Spanish
# -> 'fr_FR' - French
# -> 'CUSTOM' - Edit the messages yourself
#
# INFORMATION! -> Some languages can be outdated
#
# Chose you language here:
language: "en_BE"



####### BETA FEATURE #######
# check positions before teleport [true | false]
check-positions: "false"
####### BETA FEATURE #######




#DON'T CHANGE THIS!!
version: "2.0.3"

############################
##########theSpawn##########
############################
#Licensed under Apache License 2.0! Plugin by supercrafter333 inspirated by MSpawns from EvolSoft!
